### ISSUE TITLE
Implementar migração dos metadados dos endereços das instituições

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/MapaDaSaude#17]
Necessário realizar migração da base de dados (egressos) do CNES (endereços).

- [x] CNES -> SAGU
- [x] SAGU -> MAPAS

**Comment by victorMagalhaesPacheco** [comment]
`ALTER TABLE cnes.profissionalvinculo ADD COLUMN estabelecimento_logradouro character varying(250);
ALTER TABLE cnes.profissionalvinculo ADD COLUMN estabelecimento_numero character varying(250);
ALTER TABLE cnes.profissionalvinculo ADD COLUMN estabelecimento_bairro character varying(250);
ALTER TABLE cnes.profissionalvinculo ADD COLUMN estabelecimento_complemento character varying(250);
ALTER TABLE cnes.profissionalvinculo ADD COLUMN estabelecimento_cep character varying(25);`

**Comment by victorMagalhaesPacheco** [comment]
Script executando em produção.

**Comment by victorMagalhaesPacheco** [comment]
`sql

CREATE TABLE public.agent_meta
(
  object_id SERIAL NOT NULL,
  key character varying(255) NOT NULL,
  value text,
  id integer NOT NULL,
  CONSTRAINT agent_meta_pk PRIMARY KEY (id),
  CONSTRAINT fk_7a69aed6232d562b FOREIGN KEY (object_id)
      REFERENCES public.agent (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
)

`

**Comment by victorMagalhaesPacheco** [comment]
Definindo have serial (metas spaces)
```sql
CREATE TABLE public.space_meta
(
  object_id integer NOT NULL,
  key character varying(255) NOT NULL,
  value text,
  id SERIAL NOT NULL,
  CONSTRAINT space_meta_pk PRIMARY KEY (id),
  FOREIGN KEY (object_id)
      REFERENCES public.space (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
)

```

**Comment by Junior-Shyko** [comment]
CREATE TABLE public.seal_relation (
	id SERIAL NOT NULL,
	seal_id int4 NULL,
	object_id int4 NOT NULL,
	create_timestamp timestamp NULL DEFAULT NULL::timestamp without time zone,
	status int2 NULL,
	object_type varchar(255) NOT NULL,
	agent_id int4 NOT NULL,
	owner_id int4 NULL,
	validate_date date NULL,
	renovation_request bool NULL,
	CONSTRAINT seal_relation_pkey PRIMARY KEY (id)
);

ALTER TABLE public.seal_relation ADD CONSTRAINT seal_relation_fk FOREIGN KEY (seal_id) REFERENCES seal(id);

**Comment by Junior-Shyko** [comment]
```
CREATE TABLE public.seal_relation (
	id SERIAL NOT NULL,
	seal_id int4 NULL,
	object_id int4 NOT NULL,
	create_timestamp timestamp NULL DEFAULT NULL::timestamp without time zone,
	status int2 NULL,
	object_type varchar(255) NOT NULL,
	agent_id int4 NOT NULL,
	owner_id int4 NULL,
	validate_date date NULL,
	renovation_request bool NULL,
	CONSTRAINT seal_relation_pkey PRIMARY KEY (id)
);

ALTER TABLE public.seal_relation ADD CONSTRAINT seal_relation_fk FOREIGN KEY (seal_id) REFERENCES seal(id);
```

**Comment by victorMagalhaesPacheco** [comment]
```sql

INSERT INTO public.seal(
            id, agent_id, name, short_description, long_description, valid_period, 
            create_timestamp, status, certificate_text, update_timestamp 
          )
    VALUES ('1', '152680', 'EGRESSOS', 'EGRESSOS', 'EGRESSOS', '50', '2019-01-01', '1', 'EGRESSOS', '2019-01-01');


INSERT INTO public.seal(
            id, agent_id, name, short_description, long_description, valid_period, 
            create_timestamp, status, certificate_text, update_timestamp 
          )
    VALUES ('2', '152680', 'EGRESSOS - RESIDÊNCIA MÉDICA', 'EGRESSOS - RESIDÊNCIA MÉDICA', 'EGRESSOS - RESIDÊNCIA MÉDICA', '50', '2019-01-01', '1', 'EGRESSOS - RESIDÊNCIA MÉDICA', '2019-01-01');



INSERT INTO public.seal(
            id, agent_id, name, short_description, long_description, valid_period, 
            create_timestamp, status, certificate_text, update_timestamp 
          )
    VALUES ('3', '152680', 'EGRESSOS - RESIDÊNCIA MULTIPROFISSIONAL', 'EGRESSOS - RESIDÊNCIA MULTIPROFISSIONAL', 'EGRESSOS - RESIDÊNCIA MULTIPROFISSIONAL', '50', '2019-01-01', '1', 'EGRESSOS - RESIDÊNCIA MULTIPROFISSIONAL', '2019-01-01');



```
