### ISSUE TITLE
"Hierarquias" das profissões de saúde 

### ISSUE THREAD

**Issue by drmarcos** [EscolaDeSaudePublica/MapaDaSaude#26]
Organizar (otimizar) as estruturas das profissões de saúde

**Comment by rafaelalima** [comment]
https://www.capes.gov.br/images/documentos/documentos_diversos_2017/TabelaAreasConhecimento_072012_atualizada_2017_v2.pdf

https://www.capes.gov.br/images/documentos/documentos_diversos_2017/TabelaAreasConhecimento_072012_atualizada_2017_v2.doc
