### ISSUE TITLE
Remover opção de login fake.

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/MapaDaSaude#31]

**Comment by uira** [comment]
@victorMagalhaesPacheco Isso aqui não é pq vcs desativaram o modo production? 

Não seria só desativar esse modo?

**Comment by victorMagalhaesPacheco** [comment]
Necessário implementar a instalação do plugin: https://github.com/secultce/MultipleLocalAuth
