### ISSUE TITLE
Reestruturação (Taxonomias, tags, Selos)

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/MapaDaSaude#33]
- [x] Taxonomias não definidas;
- [x] Tags (CBOs)
- [x] Selos (Residência médica, Egressos, Residência Multiprofissional)

**Comment by drmarcos** [comment]
Para fins acadêmicos e uso não profissional, a SNOMED CT está disponível gratuitamente por meio do navegador do Sistema Unificado de Linguagem Médica (Unified Medical Language System, UMLS), bastando fazer o registro no endereço: https://uts.nlm.nih.gov/home.html.
