### ISSUE TITLE
No acesso online não consegui fazer um cadastro.

### ISSUE THREAD

**Issue by Junior-Shyko** [EscolaDeSaudePublica/MapaDaSaude#40]
![Captura de tela de 2019-12-12 08-54-26](https://user-images.githubusercontent.com/7341117/70710137-52192e00-1cbd-11ea-94c9-3fc73b727734.png)
Erro: Um erro inesperado aconteceu

**Comment by victorMagalhaesPacheco** [comment]
Problema de permissão do usuário no banco.
