### ISSUE TITLE
Verificar erro de permissão da Segunda Fase.

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/MapaDaSaude#43]

**Comment by Junior-Shyko** [comment]
Passos para realizar 1ª e subs oportunidades.

1. Criar oportunidade já com todas as fases que precisa ser criado;
2. Ao final de cada etapa deve publicar a etapa;
3. Deve acessar a próxima etapa e escolher como o candidato participará da etapa seguinte.
4. Escolher como **rascunho** ou importar **inscrições** 
![Captura de tela de 2019-12-23 10-19-49](https://user-images.githubusercontent.com/7341117/71360371-6dfaba80-256e-11ea-82f8-6eb5163dd22a.png)
5.Pronto! A Etapa está habilitada para o candidato.
