### ISSUE TITLE
Mover sidebar profissionais para nova aba "Profissionais de saúde"

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/MapaDaSaude#44]
- [x] Adicionar quantitativo por especialidade
- [ ] Ajustar tamanho do avatar

**Comment by rmadev-master** [comment]
Criada a branch **hotfix-layoutEsp**, IP 10.17.0.249, rmadev

**Comment by camilaccolares** [comment]
Criado e atualizado o ícone de identificação do site (.ico). 
Endereço: [raiz]/src/protected/application/themes/{Tema}/assets/img/favicon.ico

**Comment by rmadev-master** [comment]
Criado e atualizado o ícone de identificação do site (.ico).
Endereço: [raiz]/src/protected/application/themes/{Tema}/assets/img/favicon.ico

**Comment by rmadev-master** [comment]
Adaptada a tela de exibição do Espaço para "encher" a tela.

**Comment by rmadev-master** [comment]
- Quantitativo de Agestes :: ({{group.relations.length}}) -> [raiz]/src/protected/application/themes/BaseV1/layouts/parts/related-agents.php;
- Erros(cache) :: ('app.useAssetsUrlCache' => false | 'mergeScripts' => true | 'mergeStyles' => false) : [raiz]/src/protected/application/conf/conf-base.php;
- Histórico ($this->part('history.php', array('entity' => $entity))) : [raiz]/src/protected/application/themes/BaseV1/views/space/single.php
