### ISSUE TITLE
Nova prioridade 1: Implementar ambiente de homologação do mapas

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/MapaDaSaude#56]
Para realizar a publicação do ambiente de desenvolvimento do Mapas (homologação) é necessário: 
-  [x] Solicitar a ETICE um novo subdomínio (mapasdev.esp.ce.gov.br);
- [x] Configurar o GIT (homologa) para DEPLOY.

**Comment by victorMagalhaesPacheco** [comment]
Para realizar a publicação do ambiente de desenvolvimento do Mapas (homologação) é necessário: 
-  [ ] Solicitar a ETICE um novo subdomínio (mapasdev.esp.ce.gov.br);
 - [ ] Publicar o METABASE público (externo), pois o mapa usa o o METABASE (iframe) (metabase.esp.ce.gov.br). 
 - [ ] Migrar o METABASE para um novo servidor de produção, pois no momento está em um DESKTOP por falta de espaço.
- [ ] Configurar o GIT (homologa) para DEPLOY.

**Comment by uira** [comment]
@victorMagalhaesPacheco Não seria mais eficiente solicitarmos um dev.esp.ce.gov.br e criarmos sub-domínios ou subpastas dos projetos?

**Comment by victorMagalhaesPacheco** [comment]
@uira, não pois cada projeto tem suas especificidade, por exemplo 
mapas  - linguagem versão x, banco versão Y 
logincidadao  - linguagem versão A, banco versão B
SAGU -  linguagem versão C, banco versão D
e etc.

**Comment by uira** [comment]
@victorMagalhaesPacheco Sim, mas estamos falando de duas coisas diferentes:

- vc tá falando das máquinas.
- eu to falando do endereço.

**Comment by victorMagalhaesPacheco** [comment]
@uira então não consegui entender sua colocação.

**Comment by victorMagalhaesPacheco** [comment]
```sh

#!/bin/bash
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ "master" = "$branch" ]; then
        export GIT_WORK_TREE=/DIRETORIO/mapadasaude/
	git checkout -f $branch
	echo 'Alterações realizadas em produção'
    fi

    if [ "develop" = "$branch" ]; then
        export GIT_WORK_TREE=/DIRETORIO/mapadasaude-dev/
        git checkout -f $branch
	echo 'Alterações realizadas em homologação'
    fi

done


```
