### ISSUE TITLE
Adaptação do Sistema de Seleções p/ Edital 27

### ISSUE THREAD

**Issue by Junior-Shyko** [EscolaDeSaudePublica/MapaDaSaude#60]
Verificar falhas e melhorias no sistema.

**Comment by Junior-Shyko** [comment]
Commits sendo enviado para http://10.17.0.68/espce/p-sacs

**Comment by rmadev-master** [comment]
**Última atualização:** http://10.17.0.68/espce/p-sacs/commit/b0106ecab122e65e30e0912c2708cb9eb03efd7a
