### ISSUE TITLE
Criar tema da saúde

### ISSUE THREAD

**Issue by Junior-Shyko** [EscolaDeSaudePublica/MapaDaSaude#64]
Fazer o clone do repositório https://github.com/govce/mapasculturais e criar o tema saude com base no layout já criado nesse mesmo repositório
Layout do tema: https://devmapas.esp.ce.gov.br/

**Comment by Junior-Shyko** [comment]
Tarefa realizada.

**Comment by uira** [comment]
@Junior-Shyko 👏🏽👏🏽👏🏽
