### ISSUE TITLE
Dúvidas do mapas

### ISSUE THREAD

**Issue by Junior-Shyko** [EscolaDeSaudePublica/MapaDaSaude#66]
Alguns pontos de demandas para ser esclarecido com **Rafael da Hacklab**

https://docs.google.com/document/d/11owEiiQAeo3v_faInpy6mAV_jZZ0rgBjD6fUtyTThdg/edit?usp=sharing

**Comment by uira** [comment]
@Junior-Shyko @rafaelchavesfreitas

**Comment by Junior-Shyko** [comment]
Colocar em prática as respostas do @rafaelchavesfreitas

**Comment by Junior-Shyko** [comment]
Dúvidas atuais esclarecidas.
