### ISSUE TITLE
Corrigir permissões

### ISSUE THREAD

**Issue by Junior-Shyko** [EscolaDeSaudePublica/MapaDaSaude#78]
Tem que ser corrigido a permissão de usuários poderem editar projetos, eventos, agentes e oportunidades.

**Comment by Junior-Shyko** [comment]
Constatado que com um novo clone do repositório oficial o problema de editar projetos, eventos, agentes e oportunidades não tem, significa que é um problema específico e não um problema geral ou mesmo da classe keycloak.

**Comment by victorMagalhaesPacheco** [comment]
Não será mais necessário, pois na nova instância o problema está resolvido.
